version: "3"
services:

  jenkins:
    container_name: jenkins
    image: imleo/jenkins-withdocker
    ports:
      - 16000:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /deployments:/deployments
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker-compose:/usr/bin/docker-compose
